server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yurekesley/config-server-repo
          search-paths:
            - movie-catalog-service
            - movie-info-service
            - ratings-data-service